config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
    resources :users
  end
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  # has_one :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :comment))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to(post_path(@post))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.name %>: </strong>
          <%= comment.comment %>
        </p>
      </div>
    </div>

    <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: {confirm: "Are you sure?"} %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :name, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :comment, input_html: {class: 'textarea'}, wrapper: false, label_html: {class: 'label'} %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogOnRails</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<section class="hero is-info is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to 'Blog Posts', root_path, class: "navbar-item" %>
          <%= link_to 'Blog Users', users_path, class: "navbar-item" %>
          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to "Create new post", new_post_path, class: "navbar-item" %>
            <%= link_to "Create new user", new_user_path, class: "navbar-item" %>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-2">
        <%= yield :page_title %>
      </h1>
      <p class="subtitle is-6 is-pulled-right">Blog made with&nbsp;❤️&&nbsp;☕️&nbsp;by <a href="http://linkedin.com/in/jasmeetsinghbhatia">Jasmeet Singh</a></p>
    </div>
  </div>
</section>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<dev class="section hero is-light">
  <%= simple_form_for @post do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :title, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <%= f.input :content, input_html: {class: 'textarea'}, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>
    <%= link_to 'Back', :back, class: "button is-danger" %>
  <% end %>
</dev>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit post" %>

<%= render 'form'%>

app/views/posts/index.html.erb
<% content_for :page_title, "Blog Posts" %>

<section class="section">
  <div class="container">
    <% @post.each do |post| %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4">
                <%= link_to post.title, post %>
              </p>
            </div>
            <!-- Right Side edit/delete buttons-->
            <div class="level-right">
              <p class="level-item">
                <%= link_to "Edit", edit_post_path(post), class: "button is-light is-small" %>
              </p>
              <p class="level-item">
                <%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-danger is-small" %>
              </p>
            </div>
          </div>
          <div class="content">
            <%= post.content %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<% content_for :page_title, "New post" %>

<%= render 'form'%>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
  <div class="container">
    <nav class="level">
      <!-- Left Side-->
      <div class="level-left">
        <p class="level-item">
          <%= link_to "Back", :back, class: "button is-primary" %>
        </p>
      </div>

      <!-- Right Side-->
      <div class="level-right">
        <p class="level-item">
          <%= link_to "Edit", edit_post_path(@post), class: "button is-light" %>
        </p>
        <p class="level-item">
          <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-danger" %>
        </p>
      </div>
    </nav>
    <hr/>
    <div class="content">
      <%= @post.content %>
    </div>
    <hr/>
  </div>
</section>

<section class="section comments">
  <div class="container">
    <h2 class="subtitle is-5"><strong> <%= @post.comments.count%></strong> comments</h2>
    <%= render @post.comments%>
    <div class="comment-form">
      <hr />
      <h3 class="subtitle is-3">Leave a reply</h3>
      <%= render 'comments/form' %>
    </div>
  </div>
</section>

app/views/users/_form.html.erb
<dev class="section hero is-light">
  <%= simple_form_for @user do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :name, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <%= f.input :email, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>
    <%= f.button :submit, class: "button is-danger" %>
    <%= link_to 'Back', :back, class: "button is-primary" %>
  <% end %>
</dev>

app/views/users/edit.html.erb
<% content_for :page_title, "Edit user" %>

<%= render 'form'%>

app/views/users/index.html.erb
<% content_for :page_title, "Blog Users" %>

<section class="section">
  <div class="container">
    <% @users.each do |user| %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4">
                <%= link_to user.name, user %>
              </p>
            </div>
            <!-- Right Side edit/delete buttons-->
            <div class="level-right">
              <p class="level-item">
                <%= link_to "Edit", edit_user_path(user), class: "button is-light is-small" %>
              </p>
              <p class="level-item">
                <%= link_to "Delete", user_path(user), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-danger is-small" %>
              </p>
            </div>
          </div>
          <div class="content">
            <%= user.email %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/users/new.html.erb
<% content_for :page_title, "New user" %>

<%= render 'form'%>

app/views/users/show.html.erb
<% content_for :page_title, @user.name %>

<section class="section">
  <div class="container">
    <nav class="level">
      <!-- Left Side-->
      <div class="level-left">
        <p class="level-item">
          <%= link_to "Back", :back, class: "button is-primary" %>
        </p>
      </div>

      <!-- Right Side-->
      <div class="level-right">
        <p class="level-item">
          <%= link_to "Edit", edit_user_path(@user), class: "button is-light" %>
        </p>
        <p class="level-item">
          <%= link_to "Delete", user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-danger" %>
        </p>
      </div>
    </nav>
    <hr/>
    <div class="content">
      <%= @user.email %>
    </div>
    <hr/>
  </div>
</section>